sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
cache:
  directories:
  - node_modules
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
script:
- npm run build:prod
deploy:
  node_js: '12'
  skip_cleanup: true
  on:
    branch: release/*
  provider: npm
  email: developer@uiza.io
  api_key:
    secure: OhJmy2eIe0Mq3uXnfWEM/z5QbYD1MLBggX6LhSLLa459qSk1dxxtvgkUbLn2v2nhJvAsa6cf8a93vhOc0IVVhliXxDeMYqbDEHt/ez0kamVIc0jDdwTVoDyy4aRDqg+qB2TILAFprNMMfZi/BIeMehqpJ2wOrSxo20woItgt0lPenVth9NVgURp77G5H+j0YRdGO0TDXHoQRPYUG2Y1lBsrNbQpaWLe1vThSDHqB6d26tfp958rZcNcmrZhlHgTnZCcUh4fXEtKsa1/sVr2jLVmS3xgnlG2XJCVyI5atj8DEH2CEvU3mNteXxIVJzHSdxHDfqGexNo3IY7kQn2rzguSkRAnNhHZQqgg9IJcpX3ghBKvSE8t3HQ7b/4n0/3eFfWevOpZOhOU6gDmJvFZId/AUhraaUjTi4c9q31Bao/6vXBdxdd4bvtdV9r2AW5uOvqeSU/guzTMrMzBWGUmbodVb2HzjK9+4dWmNOGO4Iivd7k1SUUVBUiJiyECpPEEsErbu1omzgiPViZQdEL2Jm2KYB/49MHVNJF1Yl4En4Dq+XlBEUQjj3L0A7LUc77bt49cibrRXgde/3m6ydX/YWctNGFuKeNAfskCfnnEAt95wJUK6vJcZeTu6pGOeLShp3cZz8ejBwr0n8L4Ln5xLmI1K1czxF3SjgcQwToCgLj0=
notifications:
  slack:
    secure: SQJkIhHTiX6Ls5u7eajm1PqsOnWQ8dclxsKFY5aUuuxWSHG0/R6tEvyktelAOhBQKZ1p8B4gWs4HjbDRWh5SeogytOyAvrhKJaX0+DG+eJoHOVBD8xzow/p4Gj6u9bMwlWYc+uj8WnJPMqYcx2lciWIL156CEsd/CbnvFQOlA2hdMH+gLd46nb4bBHc2YS6qC6YHqvsSZPiMLaPo8hk/LDZeMC3+g0oChLRyJIaC5bIh17lVAgTccbYy4jBooM3ryckYnVZvhKlAPfgZ8bP/kXia7FMkOi8vhtoi3V8pekif44ii4CfQg3+QEpn9cGSHfBrveIvqOAwribdh4YvqAOfviapbGnJBtsfX3L/rlCYfUirfhEJ6Njz9zKpTo7yafdvndd/47zkKz3cNzpyrodIqG24DIsB700Gphyss9s95rf68dItKME9ZlGxRTBGbI+J33FvEfAnCHhxB8bFnWQYc/GIXd06jhHVSXgugBesNgeZYuKt1k3UP8L7x4DK/Yk+q3ZGHktOmNbESw5LK8D1E/elvhqM4SgitTtVvi+d/9fMUlTdcxRPUGqH87Bt285eWUlWyGlpKECBhcs0Y2XOukkw3pszUBVugAaueppFj/pJJt0a9zYTZHCr8tmJCKYY3wK3uvnpsVLb19vIwUybQ5xbsCpu9y4SVvjRurxA=
