sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
cache:
  directories:
  - node_modules
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
script:
- npm run build:prod
deploy:
  node_js: '12'
  skip_cleanup: true
  on:
    branch: release/*
  provider: npm
  email: developer@uiza.io
  api_key:
    secure: o8ESJdAVeX9x8TqtHLSPtG+kQBzpR5lFhPP5hevaNRmHiNBJPd2Wk7YQTVZ0GEv6A23NSPXXfrv8JqPIbxn6X/ArCB31u7bG3IeXw4+VgKoWsQub0pz6Eiu8zcdlUhf7BFURDHDNUhGOUjR0Xfjg9fsN1IJBt/KYQteVIhuLfRK44uh1/70YREBR1E8T8O7M+/Ixk1j9b53Xk60TPV2aUyjVhcvOGIJL8IIl6ozq8C8hsqTuRXnfE92ZiWHJXydeUYY8R8lhH7/mGWKUwTZ6oTQ+PpftPF0iVm6n30v+ANBwpkip03L8Pv2sulqi18SRpwcUZsnOOZhX3JYoHNUH+oW3n0o2Wx0wCesUpI69+8ozQ1J+ZkFeBi7tP9bEbiEgndCa78Wne4mRcbg63oOpZaHg3ACIFHBCRsgWQaL+y6xld47yAbfWuNODKMwFFgqf3fXDCr4fE8JSzLEP5nqNrKOlMHCdh4REvLEcveLxJuiLr4fqZLmJ7phkHPyJUoeiqJw31xeYsAtehS+j+Zq1cbyqj7o0qYAQVtsl/cOWatdJ3yTOB6sIWch4r91P+vh47pT2KPZ0IYwLQhj4aKpCnud/HSbZMAKxjjrQcfIpOSZnsJDx0pEBLqy7xAF5Gk2hoJsZoobgN0+TaCkPpHgry5dfDYfzXtz5MT3LFjwLa1E=
notifications:
  slack:
    secure: SQJkIhHTiX6Ls5u7eajm1PqsOnWQ8dclxsKFY5aUuuxWSHG0/R6tEvyktelAOhBQKZ1p8B4gWs4HjbDRWh5SeogytOyAvrhKJaX0+DG+eJoHOVBD8xzow/p4Gj6u9bMwlWYc+uj8WnJPMqYcx2lciWIL156CEsd/CbnvFQOlA2hdMH+gLd46nb4bBHc2YS6qC6YHqvsSZPiMLaPo8hk/LDZeMC3+g0oChLRyJIaC5bIh17lVAgTccbYy4jBooM3ryckYnVZvhKlAPfgZ8bP/kXia7FMkOi8vhtoi3V8pekif44ii4CfQg3+QEpn9cGSHfBrveIvqOAwribdh4YvqAOfviapbGnJBtsfX3L/rlCYfUirfhEJ6Njz9zKpTo7yafdvndd/47zkKz3cNzpyrodIqG24DIsB700Gphyss9s95rf68dItKME9ZlGxRTBGbI+J33FvEfAnCHhxB8bFnWQYc/GIXd06jhHVSXgugBesNgeZYuKt1k3UP8L7x4DK/Yk+q3ZGHktOmNbESw5LK8D1E/elvhqM4SgitTtVvi+d/9fMUlTdcxRPUGqH87Bt285eWUlWyGlpKECBhcs0Y2XOukkw3pszUBVugAaueppFj/pJJt0a9zYTZHCr8tmJCKYY3wK3uvnpsVLb19vIwUybQ5xbsCpu9y4SVvjRurxA=
